FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/.output ./.output
ENV NITRO_PORT=3001
ENV PORT=3001
EXPOSE 3001
CMD ["node", "./.output/server/index.mjs"]
